# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20170330_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='album_logo',
            new_name='logo',
        ),
    ]
